# Generated by Django 2.0.2 on 2018-03-09 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='key',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
