# Generated by Django 2.0.2 on 2018-03-06 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_type',
        ),
        migrations.DeleteModel(
            name='VehicleMake',
        ),
        migrations.DeleteModel(
            name='VehicleModel',
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
        migrations.DeleteModel(
            name='VehicleType',
        ),
    ]
